### ISSUE TITLE
Uncaught TypeError: Cannot read property 'GridOptionsWrapper' of undefined(…)

### ISSUE THREAD

**Issue by kashban** [ceolter/ag-grid-ng2#68] opened 2016-10-18 14:53 UTC
Heyas, 

I included ag-grid-ng2 into an Ionic 2 RC.0 app and stumble over this error:

> Uncaught TypeError: Cannot read property 'GridOptionsWrapper' of undefined(…)

The code in question:

```
var LoggerFactory = (function () {
    function LoggerFactory() {
    }
    LoggerFactory.prototype.setBeans = function (gridOptionsWrapper$$1) {
        this.logging = gridOptionsWrapper$$1.isDebug();
    };
    LoggerFactory.prototype.create = function (name) {
        return new Logger(name, this.logging);
    };
    __decorate$127([
        __param$2(0, context_2$1.Qualifier('gridOptionsWrapper')), 
        __metadata$22('design:type', Function), 
--------->
        __metadata$22('design:paramtypes', [gridOptionsWrapper_1$2.GridOptionsWrapper]), 
--------->
        __metadata$22('design:returntype', void 0)
    ], LoggerFactory.prototype, "setBeans", null);
    LoggerFactory = __decorate$127([
        context_1$4.Bean('loggerFactory'), 
        __metadata$22('design:paramtypes', [])
    ], LoggerFactory);
    return LoggerFactory;
})();
```

Ionic 2 RC.0 uses "es2015" as module which might be the issue here since the example uses "commonjs". Unfortunately changing my project to "commonjs" brings up other issues, so I'd rather fix the issue above if possible. 

The component I am using ag-grid with looks like this:

.ts:

```
import { Component, Input, Output, AfterViewInit, EventEmitter } from '@angular/core';
import { Events } from 'ionic-angular';
import { GridOptions } from 'ag-grid/main';
import 'ag-grid-enterprise/main';

// import { NavController } from 'ionic-angular';

/*
  Generated class for the ProcessPostbox component.
  Created by U0002331 (Jürgen Wahlmann)

  Shows a workorder postbox with accordeon header, search field and a grid of workorders

  @param showPostbox: true: Show postbox, false, hide this postbox
  @param state: State of process this postbox represents
*/

const LOG_PREFIX = 'ProcessPostbox: ';

@Component({
  selector: 'process-postbox',
  templateUrl: 'process-postbox.html'
})
export class ProcessPostbox implements AfterViewInit {

  @Input() state: string;
  @Input() title: string;
  @Input() workorderCount: number = 0;
  @Input() postboxSelected: string;
  @Input() filterlabel: string = '';
  @Input() columnDefs: any[];
  @Input() rowData: any[];

  @Output() onTitleClicked = new EventEmitter();
  @Output() onGridRowSelected = new EventEmitter();
  @Output() onGridDoubleClicked = new EventEmitter();
  @Output() onGridReady = new EventEmitter();

  quickFilterText: string = '';
  gridSelectedRowId: number;
  gridSelectedRowUserTaskId: string;

  private gridOptions: GridOptions;
  private rowCount: string;

  constructor(public events: Events) {
    console.log(LOG_PREFIX + 'ProcessPostbox constructor called.');
    this.gridOptions = <GridOptions>{};
  }

  /**
   * After initializing the View inject grid
   */
  ngAfterViewInit() {

  }

  /**
   * Title clicked, inform parent component
   */
  titleClicked() {
    this.onTitleClicked.emit(this.state);
  }

  workOrderRead(args) {
    // this.ngAfterViewInit();
  }

  ngOnChanges(changes) {
    console.log(LOG_PREFIX + 'ngOnChanges: ' + JSON.stringify(changes));
    //    if (changes.postboxSelected != null || changes.gridDef != null)
    //       this.ngAfterViewInit();
    // Called right after our bindings have been checked but only
    // if one of our bindings has changed.
    //
    // changes is an object of the format:
    // {
    //   'prop': PropertyUpdate
    // }
  }
  private calculateRowCount() {
    if (this.gridOptions.api && this.rowData) {
      var model = this.gridOptions.api.getModel();
      var totalRows = this.rowData.length;
      var processedRows = model.getRowCount();
      this.rowCount = processedRows.toLocaleString() + ' / ' + totalRows.toLocaleString();
    }
  }

  private onModelUpdated() {
    console.log('onModelUpdated');
    this.calculateRowCount();
  }

  private onReady() {
    console.log('onReady');
    this.calculateRowCount();
  }

  private onCellClicked($event) {
    console.log('onCellClicked: ' + $event.rowIndex + ' ' + $event.colDef.field);
    this.onGridRowSelected.emit($event);
  }

  private onCellValueChanged($event) {
    console.log('onCellValueChanged: ' + $event.oldValue + ' to ' + $event.newValue);
  }

  private onCellDoubleClicked($event) {
    console.log('onCellDoubleClicked: ' + $event.rowIndex + ' ' + $event.colDef.field);
    this.gridSelectedRowId = $event.rowIndex;
    this.onGridDoubleClicked.emit($event);
  }

  private onCellContextMenu($event) {
    console.log('onCellContextMenu: ' + $event.rowIndex + ' ' + $event.colDef.field);
  }

  private onCellFocused($event) {
    console.log('onCellFocused: (' + $event.rowIndex + ',' + $event.colIndex + ')');
  }

  private onRowSelected($event) {
    // taking out, as when we 'select all', it prints to much to the console!!
    // console.log('onRowSelected: ' + $event.node.data.name);
    this.onGridRowSelected.emit($event);
  }

  private onSelectionChanged() {
    console.log('selectionChanged');
  }

  private onBeforeFilterChanged() {
    console.log('beforeFilterChanged');
  }

  private onAfterFilterChanged() {
    console.log('afterFilterChanged');
  }

  private onFilterModified() {
    console.log('onFilterModified');
  }

  private onBeforeSortChanged() {
    console.log('onBeforeSortChanged');
  }

  private onAfterSortChanged() {
    console.log('onAfterSortChanged');
  }

  private onVirtualRowRemoved($event) {
    // because this event gets fired LOTS of times, we don't print it to the
    // console. if you want to see it, just uncomment out this line
    // console.log('onVirtualRowRemoved: ' + $event.rowIndex);
  }

  private onRowClicked($event) {
    console.log('onRowClicked: ' + $event.node.data.name);
  }

  private onQuickFilterChanged($event) {
    this.gridOptions.api.setQuickFilter($event.target.value);
  }

  // here we use one generic event to handle all the column type events.
  // the method just prints the event name
  private onColumnEvent($event) {
    console.log('onColumnEvent: ' + $event);
  }

}
```

*.html

```
<!--
  Generated template for the ProcessPostbox component.

  See https://angular.io/docs/ts/latest/api/core/ComponentMetadata-class.html
  for more info on Angular 2 Components.
-->
<ion-toolbar>
    <ion-segment>
        <button ion-button (click)="titleClicked()" block>
            <ion-icon name="filing"></ion-icon> &nbsp;{{title}}&nbsp;{{filterlabel}}  
            &nbsp;<ion-badge danger>{{gridDef.rowData ? gridDef.rowData.length : 0}}</ion-badge>
        </button>
    </ion-segment>
</ion-toolbar>
<ion-card [hidden]="postboxSelected !== state">
    <ion-input placeholder="Filter..." type="text" [(ngModel)]="quickFilterText"></ion-input>
    <p></p>
    <button ion-button color="primary" icon-left (click)="workOrderRead({ id: gridSelectedRowId, userTaskId: gridSelectedRowUserTaskId})"><ion-icon name="eye"></ion-icon>Anzeigen</button>
    <ag-grid-ng2 #agGrid style="width: 100%; height: 500px;" class="ag-material" [gridOptions]="gridOptions" [columnDefs]="columnDefs" [showToolPanel]="showToolPanel" [rowData]="rowData" enableColResize enableSorting enableFilter groupHeaders toolPanelSuppressGroups
        toolPanelSuppressValues debug rowHeight="22" rowSelection="single" (modelUpdated)="onModelUpdated()" (cellClicked)="onCellClicked($event)" (cellDoubleClicked)="onCellDoubleClicked($event)" (cellContextMenu)="onCellContextMenu($event)" (cellValueChanged)="onCellValueChanged($event)"
        (cellFocused)="onCellFocused($event)" (rowSelected)="onRowSelected($event)" (selectionChanged)="onSelectionChanged()" (beforeFilterChanged)="onBeforeFilterChanged()" (afterFilterChanged)="onAfterFilterChanged()" (filterModified)="onFilterModified()"
        (beforeSortChanged)="onBeforeSortChanged()" (afterSortChanged)="onAfterSortChanged()" (virtualRowRemoved)="onVirtualRowRemoved($event)" (rowClicked)="onRowClicked($event)" (ready)="onReady($event)" (columnEverythingChanged)="onColumnEvent($event)"
        (columnRowGroupChanged)="onColumnEvent($event)" (columnValueChanged)="onColumnEvent($event)" (columnMoved)="onColumnEvent($event)" (columnVisible)="onColumnEvent($event)" (columnGroupOpened)="onColumnEvent($event)" (columnResized)="onColumnEvent($event)"
        (columnPinnedCountChanged)="onColumnEvent($event)">
    </ag-grid-ng2>
</ion-card>
```

example columnDefs:

```
columnEvaluateDefs = [
    CONSTANTS.COLDEF_WORKORDERGROUPID,
    CONSTANTS.COLDEF_MOBILESTATE,
    CONSTANTS.COLDEF_NUMOFCOMMENTS,
    { headerName: 'ID', field: 'orderId', width: 100, filter: 'text', hide: false },
    { headerName: 'Lokationsobjekt', field: 'locationObject', width: 200, filter: 'text', hide: false },
    { headerName: 'Auftragstext', field: 'title', width: 200, filter: 'text', hide: false },
    { headerName: 'Betriebsmittel', field: 'asset', width: 200, filter: 'text', hide: false },
    { headerName: 'Zuständigkeit', field: 'competence', width: 200, filter: 'text', hide: false },
    { headerName: 'Gemeinde', field: 'community', width: 200, filter: 'text', hide: true },
    { headerName: 'Ortsteil', field: 'district', width: 200, filter: 'text', hide: true },
    { headerName: 'Ausführungsdatum', field: 'completionDateText', width: 150, filter: 'text', hide: false }
  ];

```

CONSTANTS.ts:

```

public static COLDEF_WORKORDERGROUPID = {
        headerName: '', field: 'workOrderGroupId', width: 25,
        cellRendererFramework: {component: GroupIdCellRenderer},
        hide: false
    };

    public static COLDEF_MOBILESTATE = {
        headerName: '', field: 'mobileState', width: 25, 
        cellRendererFramework: { component: MobilestateCellRenderer}
        , hide: false
    };

    public static COLDEF_NUMOFCOMMENTS = {
        headerName: '', field: 'numberOfComments', width: 25, 
        cellRendererFramework: { component: NumOfCommentsCellRenderer },
        hide: false
    };

    public static COLDEF_DISPATCHED = {
        headerName: '', field: 'dispatched', width: 25,
        cellRendererFramework: { component: DispatchedCellRenderer }, hide: false
    };
```

Any idea how I can fix the missing gridOptionsWrapper?

**Comment by seanlandsman** [comment] 2016-11-09 15:31
I've been working on moving our ng2 support to include aot and dynamic components and have it working now. We'll be releasing it soon - I'll update once I have a beta ready for everyone

I'm not altogether sure this helps you though - ag-grid-ng2 will continue to be in commonjs in the short term.  I will see if I can include multiple exports in the next release too, which may help

thanks

**Comment by seanlandsman** [comment] 2016-11-16 19:32
hi @kashban

Please take a look at the new 7.x beta thats available - this supports both AOT and JIT mode: https://www.ag-grid.com/angular-2-beta-release/

**Comment by kashban** [comment] 2016-11-18 20:46
Hi @seanlandsman I am currently busy on two other projects but will do as soon as I get my hands on the that project in question again.

**Comment by dmarginian** [comment] 2016-11-28 19:33
@seanlandsman 
I tried  the beta (7.0.0-beta.4) and I am still seeing "Cannot read property 'GridOptionsWrapper' of undefined' when bundling with rollup.  Inspecting the bundle generated by rollup the GridOptionsWrapper code is way below the logger.js code (where the error is coming from).  I am thinking this may be related to - https://github.com/rollup/rollup/issues/995.  I will post back if I find out more.

**Comment by seanlandsman** [comment] 2016-12-02 12:03
@dmarginian thanks very much for this information - I had meant to reply earlier, apologies.

I'm planning on looking at offering rollup & webpack examples in the example project over the next couple of weeks if possible

**Comment by dmarginian** [comment] 2016-12-02 13:33
Sean,
I looked into this more and ended up hand jamming the bundled JS so that LoggerFactory did not have a dependency on GridOptionsWrapper and then I got another error that was not related to cyclical dependencies.  I concluded that rollup's commonjs plugin can't properly bundle certain libraries  - although I don't know what the root cause is.  I ended up switching to SystemJs Builder.  It is a more natural fit anyway since we are using SystemJs on the dev side.  Also, it will use rollup for es2015 modules.

**Comment by seanlandsman** [comment] 2016-12-02 13:43
thanks - as it happens we use SystemJs Builder in our examples project as I found it far easier to get up and running with very little effort

**Comment by jskrzypek** [comment] 2016-12-17 12:30
So there's no solution for rollup?

**Comment by jskrzypek** [comment] 2016-12-18 16:19
I just read the above discussion again and I went to look at the source in `ag-grid`. It seems like the circular dependency can't actually be the problem.

If you look at the source of [`ag-grid/src/ts/gridOptionsWrapper.ts`](https://github.com/ceolter/ag-grid/blob/master/src/ts/gridOptionsWrapper.ts#L21) the only instances of the symbols `Logger` and `LoggerFactory` are in the import: . They're not being used anywhere in the component. Moreover, if you look at the dist output in [`ag-grid/dist/lib/gridOptionsWrapper.d.ts](https://github.com/ceolter/ag-grid/blob/master/dist/lib/gridOptionsWrapper.d.ts) and [`ag-grid/dist/lib/gridOptionsWrapper.js](https://github.com/ceolter/ag-grid/blob/master/dist/lib/gridOptionsWrapper.js). I don't think that circularities can possibly be the issue in rollup. I'm going to dig a bit more.

It's also unclear to me why [`ag-grid/dist/lib/logger.d.ts](https://github.com/ceolter/ag-grid/blob/master/dist/lib/logger.d.ts) wouldn't have an `import { GridOptionsWrapper } from './gridOptionsWrapper';` statement...

**Comment by seanlandsman** [comment] 2016-12-18 17:01
Hi @jskrzypek - thanks for the investigation.  I was going to start picking this up next week if time allows, but in the meantime your investigation will definitely help resolve this quicker

**Comment by jskrzypek** [comment] 2016-12-18 18:51
Not a problem, though trying to figure out all of the moving pieces in aot
is driving me up the wall. :)

Assuming it's not actually a bug in the code itself or something caused by
that orphaned import, one thing I'm exploring is if it'll work to provide
es2015 versions of the ag-grid/dist/lib files using tsc's "module":
"es2015" compiler option

These files could then be provided with a module.js that does what the
main.js does but in an es2015 way, finally, adding `"module":
"./module.js"` to the `package.json` could tell rollup to use module
instead of main.

But now something else broke in my aot build process, so I probably won't
know anything on that front until tomorrow...

**Comment by avramcosmin** [comment] 2017-01-19 12:10
Hi. Any update on this? With Angular 2.4.4 & Ag-Grid 7.2.2 after rollup we still get this error.

**Comment by jskrzypek** [comment] 2017-01-19 21:42
We ended up giving up on rollup. We might go back to eventually.

One thing you might try is using rollup to separately bundle th the ag-grid
libs through rollup and typescript the same way this guide does with
angular 2

https://www.codementor.io/stevebelovarich/use-rollup-to-build-angular-2-web-apps-du1089cq5


On Thu, Jan 19, 2017, 14:10 Avram Cosmin <notifications@github.com> wrote:

Hi. Any update on this? With Angular 2.4.4 & Ag-Grid 7.2.2 after rollup we
still get this error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ceolter/ag-grid-ng2/issues/68#issuecomment-273761063>,
or mute the thread

**Comment by seanlandsman** [comment] 2017-02-14 14:31
closing this - support for rollup can be tracked here: https://github.com/ceolter/ag-grid-ng2/issues/112

**Closed by seanlandsman** 2017-02-14 14:31 UTC
