### ISSUE TITLE
Error: 'main.ts' is not under 'rootDir'. 'rootDir' is expected to contain all source files.

### ISSUE THREAD

**Issue by evan-carey** [ceolter/ag-grid-ng2#108] opened 2016-12-28 19:10 UTC
Building with webpack 2.2.0-rc.2 and awesome-typescript-loader 3.0.0-beta.17, I'm getting the error:
```
[at-loader] File '../node_modules/ag-grid-ng2/main.ts' is not under 'rootDir' '../src'. 'rootDir' is expected to contain all source files.
```
This is a very similar issue that was resolved by removing *.ts files when publishing to npm: 
[https://github.com/sean-perkins/nativescript-opentok/issues/8](https://github.com/sean-perkins/nativescript-opentok/issues/8)

Thanks!

**Comment by dmarginian** [comment] 2016-12-29 14:49
I am seeing this as well.  main.ts and not main.js is getting into the ag-grid-ng2 distribution.

**Comment by dmarginian** [comment] 2016-12-29 15:00
This was introduced in 7.1.0, it looks like this may be the commit:
https://github.com/ceolter/ag-grid-ng2/commit/0740b8d77fdd9f006d34b84629611834a71f698b#diff-dd6ee84635af5464bcb05b4cf3d39afc

main.ts is in the exclusions and is not being compiled.  I am sure there is a reason for this but it is resulting in an invalid distribution.

**Comment by seanlandsman** [comment] 2016-12-31 10:16
do you have a sample config I can see for how you're doing the build? the ag-grid-ng2-example has an example using webpack to build the examples (which of course includes ag-grid-ng2) and it works there

The reason for the two tsconfig's is due to how angular expects metadata going forward - its a workaround to prevent other build issues, but this shouldnt stop you from being able to include it via webpack

**Comment by dmarginian** [comment] 2016-12-31 12:53
Hi Sean, I am not using webpack.  I have a small table component that I build with ngc and consume from applications.  When I build my component I end up with the ngc output directly under dist (per my config) where it should be, but the compiled js is under dist/src (related TypeScript issue - https://github.com/Microsoft/TypeScript/pull/2772).  Per the description of the TypeScript issue the rootDir flag can be added to control this, if I add that I get a failure per @evan-carey.  

The reason for this is that main.ts has not been compiled (main.js) in the ag-grid-ng2 distribution.  So when the TypeScript compiler sees:

`
import {AgGridModule} from "ag-grid-ng2/main";
`

it attempts to compile it.  If I have the rootDir option set it will blow up because ag-grid-ng2's main.ts is outside of my component's source directory.  If I leave the rootDir flag out tsc adds the src/ directory (dist/src) which causes my component to have an invalid distribution.  I attempted to work-around this by copying the js/js.maps from dist/src/ to dist which fixes my distribution but results in non-working source maps due to relative links embedded within them.

I don't have a problem with multiple tsconfig files but I am unsure of why the ag-grid-ng2 barrel (main.ts) has been excluded from compilation in tsconfig-src.  This results in this file never being compiled which doesn't seem correct.

My tsconfig.jsons:

`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "types": [],
    "declaration": true,
    "outDir": "../dist"
  },
  "files": [
    "table.module.ts",
    "index.ts",
    "typings/index.d.ts"
  ],
  "angularCompilerOptions": {
    "genDir": "../dist"
  }
}
`

**Comment by dmarginian** [comment] 2017-01-01 01:12
Related discussion over at the TypeScript project:

- https://github.com/Microsoft/TypeScript/issues/6964
- https://github.com/Microsoft/TypeScript/issues/12320

**Comment by seanlandsman** [comment] 2017-01-01 11:33
ok, I understand the issue - and see the problem.

Long story short - these changes were done to provide a fix for this issue https://github.com/angular/angular/issues/13307

But this shouldn't have caused a problem for users in a minor release, so I'll re-publish this excluding main.ts from the root directory. This will be done after the new year break, so tuesday probably.

In 8x I'll rework the way the exports are done - these changes were meant to be non-breaking for existing users (ie the way things were imported wouldnt have to change) but has obviously caused problems for certain edge cases like yours (& @evan-carey)

If you can provide a reproducable build config I can use to test this before I publish that would be great (to verify that this works for you), but if you can't (and I understand that this isn't always possible) I'll do a release regardless during the week with main.ts excluded from the npm publish

**Comment by dmarginian** [comment] 2017-01-01 15:20
Thanks @seanlandsman.  Is the plan for 8.x to change the location of the imports to avoid this?  I am going to create an issue for the TypeScript guys as I don't see how an external library should affect my components distribution - that just doesn't seem right.  

I created a git repo that replicates the problem, follow the directions in the README - https://github.com/dmarginian/ag-grid-ng2-ts-issue.

**Comment by dmarginian** [comment] 2017-01-01 16:03
FYI - https://github.com/Microsoft/TypeScript/issues/13240

**Comment by evan-carey** [comment] 2017-01-01 21:16
Thanks @seanlandsman and @dmarginian for looking into this. My temporary solution was to remove the "rootDir" option from my tsconfig.json. I unfortunately cannot share my build config, but I will confirm that the new release works with it. Thanks again!

**Comment by dmarginian** [comment] 2017-01-02 00:23
@seanlandsman and @evan-carey this should also be resolved if you update your version of TypeScript to 2.1.  I am going to update all of my components to use 2.1 so I don't need a fix.

**Comment by seanlandsman** [comment] 2017-01-03 10:18
@evan-carey @dmarginian 

"Is the plan for 8.x to change the location of the imports to avoid this?" <- not specifically for this problem, but to remove the need to have 2 builds 

I've tried your repo and typescript 2.1 resolves this issue - this coupled with the fact I don't believe this is our problem (in that I dont thin typescript should be trying to compile/use anything other than .d.ts files in libraries means I won't do a change now.

Can you both please verify that 2.1 resolves this for you and let me know?

**Comment by dmarginian** [comment] 2017-01-03 15:03
@seanlandsman, if all that mattered was tsc, updating typescript to 2.1 would fix the problem.  However, I also need angular metadata, and ngc is pegged to a 2.0.x version of TypeScript.  So, when I run ngc I encounter the same problem.  I thought this could be resolved by bumping TypeScript to 2.1.x and running both ngc (for the metadata) and tsc.  However, the presence of TypeScript 2.1 conflicts with ngc and the metadata is not generated.  

I have pushed an update to the git repo I created to demonstrate this.  The TypeScript version is set to 2.0.x.  Run "npm install" and you will see the metadata produced in the ngc directory.  Next, clear out node_modules and update the typescript version to 2.1.x.  Run "npm install" and you will see that there is no metadata in the ngc directory.  

I agree with you, that this is not an ag-grid-ng2 issue.  However, it will affect anyone building consumable components based on ag-grid-ng2 (unless maybe they are on angular 4.x beta.).  If you are fine with this and don't want to release an update I understand.  I wouldn't mind going through my code and modifying my imports if you can tell me what they are going to be in the future so I don't have to change my code twice (import {AgGridModule} from "ag-grid-ng2/dist/aggrid.module";?).  Thanks.

**Comment by seanlandsman** [comment] 2017-01-03 16:46
Thanks, that makes sense

I've released 7.1.2-beta.1 which includes this change for you (amongst other minor changes). I've tried it with your repo and it installs fine - have a try and let me know if you're happy with the changes.

@evan-carey @dmarginian

**Comment by evan-carey** [comment] 2017-01-03 17:24
@seanlandsman I was still getting the error using typescript 2.1.4 and ag-grid-ng2 7.1.1.

7.1.2-beta.1 resolves the issue for me though. Thanks again!

I'm comfortable closing this issue whenever @dmarginian is.

**Comment by dmarginian** [comment] 2017-01-03 20:46
@seanlandsman 7.1.2-beta.1 fixes the issue.  Thanks for being so flexible.

**Comment by seanlandsman** [comment] 2017-01-04 09:23
Well that will teach me to rush out a beta (good job its a beta) and trust an IDE import.

I've released 7.1.2-beta.2 to fix this - note that I'm pretty sure this fixes it (the problem was obvious), but I am unable to test it with your repo (ngc runs fine with .1)

Thanks for feeding this back

**Comment by dmarginian** [comment] 2017-01-04 14:30
@seanlandsman 7.1.2-beta.2 resolves all issues.  Thanks again!

**Comment by seanlandsman** [comment] 2017-01-04 16:39
great, thanks - we'll do a full release later in the week (will be 7.1.3) to resolve this officially

**Closed by seanlandsman** 2017-01-04 16:39 UTC

**Comment by smulanry** [comment] 2017-09-06 06:01
@seanlandsman we are experiencing this issue with our build setup, starting with 10.0.  It looks to be the caused by [https://github.com/ag-grid/ag-grid-angular/commit/d99ff4fe5546f3a1211cddd77fa2bf6bd482c45a].  

Was there a reason why the main.ts file was added to the the npm package?  If you are including it to assist with debugging could we move it outside of the root folder to not interfere with the resolving of main.d.ts file

**Comment by seanlandsman** [comment] 2017-09-06 16:06
This doesn't seem like a deliberate change in npmignore - I'll revert this to continue to ignore main.ts

**Comment by smulanry** [comment] 2017-09-07 17:26
Thanks @seanlandsman any idea, when this change to the package will be released?

**Comment by seanlandsman** [comment] 2017-10-06 08:42
hi - this has been released, you should see it in the latest version of ag-grid-angular

thanks
