### ISSUE TITLE
Can't bind gridOptions since it isn't a known property of ag-grid-ng2 and more

### ISSUE THREAD

**Issue by azakrytnoi** [ceolter/ag-grid-ng2#125] opened 2017-02-07 14:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Page fails to load, giving an error message:
Unhandled Promise rejection: Template parse errors:
Can't bind to 'gridOptions' since it isn't a known property of 'ag-grid-ng2'.
1. If 'ag-grid-ng2' is an Angular component and it has 'gridOptions' input, then verify that it is part of this module.
2. If 'ag-grid-ng2' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("r: both;"></div>

        <ag-grid-ng2 #agGrid style="width: 100%; height: 350px;" class="ag-fresh" [ERROR ->][gridOptions]="gridOptions" [showToolPanel]="showToolPanel" [rowData]="rowData" enableColResize enabl"): RichGridComponent@41:82
Can't bind to 'showToolPanel' since it isn't a known property of 'ag-grid-ng2'.
1. If 'ag-grid-ng2' is an Angular component and it has 'showToolPanel' input, then verify that it is part of this module.
2. If 'ag-grid-ng2' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("g-grid-ng2 #agGrid style="width: 100%; height: 350px;" class="ag-fresh" [gridOptions]="gridOptions" [ERROR ->][showToolPanel]="showToolPanel" [rowData]="rowData" enableColResize enableSorting enableFilter groupH"): RichGridComponent@41:110
... rest skipped...
**Expected behavior**

As this is direct copy from example provided  by ag-grid website - expected to at least show the grid.

**Minimal reproduction of the problem with instructions**

Create the angular2 module, (copy/paste from github examples project). Build script gives error
**_src/client/app/agtable/agtable.component.ts(212,114): error TS7017: Index signature of object type implicitly has an 'any' type._**
function countryCellRenderer(params: any) {
    let flag = '<img border=\'0\' width=\'15\' height=\'10\' style=\'margin-bottom: 2px\' src=\'images/flags/' + **_RefData.COUNTRY_CODES[params.value]_** + '.png\'>';
    return flag + ' ' + params.value;
}

but continues. While loading app in the brrowser: 
Unhandled Promise rejection: Template parse errors:
Can't bind to 'gridOptions' since it isn't a known property of 'ag-grid-ng2'.
1. If 'ag-grid-ng2' is an Angular component and it has 'gridOptions' input, then verify that it is part of this module.
2. If 'ag-grid-ng2' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("r: both;"></div>

        <ag-grid-ng2 #agGrid style="width: 100%; height: 350px;" class="ag-fresh" [ERROR ->][gridOptions]="gridOptions" [showToolPanel]="showToolPanel" [rowData]="rowData" enableColResize enabl"): RichGridComponent@41:82
Can't bind to 'showToolPanel' since it isn't a known property of 'ag-grid-ng2'.
1. If 'ag-grid-ng2' is an Angular component and it has 'showToolPanel' input, then verify that it is part of this module.
2. If 'ag-grid-ng2' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("g-grid-ng2 #agGrid style="width: 100%; height: 350px;" class="ag-fresh" [gridOptions]="gridOptions" [ERROR ->][showToolPanel]="showToolPanel" [rowData]="rowData" enableColResize enableSorting enableFilter groupH"): RichGridComponent@41:110

**What is the motivation / use case for changing the behavior?**

I need a flexible table in my application.

**Please tell us about your environment:**

Centos7, node v7.4.0, npm v4.0.5
dependencied from package.json:
  "dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.1",
    "ag-grid": "^7.2.2",
    "ag-grid-ng2": "^7.2.2",
    "core-js": "^2.4.1",
    "css-loader": "^0.26.1",
    "file-loader": "^0.10.0",
    "intl": "^1.2.5",
    "rxjs": "~5.0.3",
    "systemjs": "0.19.41",
    "url-loader": "^0.5.7",
    "webpack": "^2.2.1",
    "zone.js": "^0.7.2"

* **ag-grid-ng2 version:** 2.0.X

v7.2.2

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

not used

* **Angular version:** 2.0.X

v2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, didn't try others

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.9

**Comment by seanlandsman** [comment] 2017-02-07 15:25
Have you followed the instructions on the docs https://www.ag-grid.com/best-angular-2-data-grid?

**Comment by seanlandsman** [comment] 2017-02-08 14:48
closing as I cannot reproduce

**Closed by seanlandsman** 2017-02-08 14:48 UTC
Labels: need repro

**Comment by HarshaVardhanPVK** [comment] 2017-12-04 09:19
Getting same error while writing test specs. While running application everything is fine.
