### ISSUE TITLE
Values not retained in full row edit scroll

### ISSUE THREAD

**Issue by sskmail14** [ceolter/ag-grid-ng2#120] opened 2017-01-26 14:00 UTC
Values not retained in full row edit on scroll.

I have a scroll-able ag-grid. I have enabled `editType = 'fullRow'` full row edit.
I have changed the value in a text box of first column.
I scroll to right to change rest of the columns
When I scroll back to left value that are changed[first column] is not retained.

**Comment by seanlandsman** [comment] 2017-01-26 14:18
You can track this issue on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline/

The issue is AG-196

**Comment by seanlandsman** [comment] 2017-01-26 14:19
As a workaround, you can turn the column virtualisation off when editing full rows gridOptions. suppressColumnVirtualisation = true, but this may have a detrimental impact on performance

**Comment by sskmail14** [comment] 2017-01-26 14:30
@seanlandsman  Am using the rowmodel as pagination

**Comment by seanlandsman** [comment] 2017-01-26 14:35
the rowmodel doesnt matter here - you can still turn the col virtualisation off

I've just learnt that there is already an issue open for this: https://github.com/ceolter/ag-grid/issues/1424

Closing this issue - please refer to the issue above to track the progress of it

**Closed by seanlandsman** 2017-01-26 14:35 UTC
Labels: bug
