### ISSUE TITLE
Make AgGrid work in offline compiler (AOT)

### ISSUE THREAD

**Issue by DzmitryShylovich** [ceolter/ag-grid-ng2#51] opened 2016-09-26 13:36 UTC
To be able to compile project in [aot mode](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) 3rd party libs need to publish `metadata.json` file.
Therefore, you need to compile this project with ngc.
```
 "angularCompilerOptions": {
    "skipTemplateCodegen": true
  }
```
Add that to tsconfig and ngc will only generate metadata files and not ngfactories.

Examples: [material2](https://github.com/angular/material2/blob/master/src/lib/tsconfig.json#L30).

https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.jhl9ftmen

**Comment by seanlandsman** [comment] 2016-09-26 17:38
Thats great - we even raised an issue for this. It seems to work - I'll confirm over the next day or two and if all is good we'll incorporate this into the build (inc metafiles)

Thanks!

**Comment by seanlandsman** [comment] 2016-09-30 12:56
Thanks for this tip - I'm afraid as far as I can see we're still blocked from offering this as aot compatible due to this issue: https://github.com/angular/angular/issues/11780

**Comment by DzmitryShylovich** [comment] 2016-09-30 15:06
Thx for your feedback.

I think you should make dynamic template compilation an optional feature. Compiler is a huge peace of angular code and one of the main benefits of aot is the ability to drop compiler from the final bundle.

For example I don't use templating feature and this situation makes me feel sad :(

**Comment by seanlandsman** [comment] 2016-09-30 16:51
yes, thats a fair request - its something we'll do, but isnt something we'll be able to get to soon I'm afraid

On the plus side, we'll be moving to typescript 2 on monday (with a new release) so you wont have your other issue (the typings issue) from then

**Comment by DzmitryShylovich** [comment] 2016-09-30 20:43
https://gitter.im/angular/angular?at=57eecd9916c3736220185690 :(

**Comment by DzmitryShylovich** [comment] 2016-09-30 21:11
After some discussion in gitter looks like RuntimeCompiler won't be supported in aot mode. So u have to decide between jit and aot users or create 2 separate projects.

**Comment by seanlandsman** [comment] 2016-10-03 17:56
Unfortunately I've come to the same conclusion - I'm working on some ideas that will allow either aot and NO dynamic component, or dynamic components and NO aot

A pity, but its a choice our users will have to make until we've another option

**Comment by seanlandsman** [comment] 2016-10-04 10:39
I've just release 6.1.1-beta - can you give it a go and see if it resolves your problem

To use it, import AgGridModule in your module (not AgGridModule.forRoot() - this will remain for non-aot/dynamic components)

**Comment by DzmitryShylovich** [comment] 2016-10-04 14:28
Sure.

**Comment by DzmitryShylovich** [comment] 2016-10-04 14:39
```
ERROR in ./src/compiled/src/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve '../../../../agNoopComponentFactory' in 'D:\Workspace\test2\src\compiled\src\app'
 @ ./src/compiled/src/app/app.module.ngfactory.ts 49:15-60
 @ ./src/main.browser.aot.ts

ERROR in [default] D:\Workspace\test2\src\compiled\src\app\app.component.ngfactory.ts:427:27 
Property 'gridOptions' is private and only accessible within class 'AgGridNg2'.

ERROR in [default] D:\Workspace\test2\src\compiled\src\app\app.module.ngfactory.ts:49:26 
Cannot find module '../../../../agNoopComponentFactory'.
```

**Comment by DzmitryShylovich** [comment] 2016-10-04 14:42
```
ERROR in ./src/compiled/src/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve '../../../../agNoopComponentFactory' in 'D:\Workspace\test2\src\compiled\src\app'
 @ ./src/compiled/src/app/app.module.ngfactory.ts 49:15-60
 @ ./src/main.browser.aot.ts

ERROR in [default] D:\Workspace\test2\src\compiled\src\app\app.component.ngfactory.ts:427:27 
Property 'gridOptions' is private and only accessible within class 'AgGridNg2'.

ERROR in [default] D:\Workspace\test2\src\compiled\src\app\app.module.ngfactory.ts:49:26 
Cannot find module '../../../../agNoopComponentFactory'.
```

**Comment by seanlandsman** [comment] 2016-10-04 14:44
I think I know what this is - instead of providing multiple betas, do you have a stripped down plunker or similar you can provide?  Otherwise I'll fix what I think is wrong here (I didnt experience this with my particular test)

**Comment by DzmitryShylovich** [comment] 2016-10-04 14:44
https://github.com/ceolter/ag-grid-ng2/blob/master/src/agGridNg2.ts#L201

Inputs, outputs, view or content child(ren), hostbindings, any field you use from the template or annotate for Angular should be public.

**Comment by seanlandsman** [comment] 2016-10-04 14:49
Interesting - I had thought the inputs array above was sufficient

**Comment by DzmitryShylovich** [comment] 2016-10-04 14:50
> do you have a stripped down plunker or similar you can provide?

it's not possible to test aot in plunkr. here's my sandbox https://github.com/DzmitryShylovich/aot-sandbox

**Comment by seanlandsman** [comment] 2016-10-04 15:00
That'll be helpful - unfortunately:

warning: remote HEAD refers to nonexistent ref, unable to checkout.

**Comment by DzmitryShylovich** [comment] 2016-10-04 15:04
Fixed. `no-universal-support` branch

**Comment by seanlandsman** [comment] 2016-10-04 15:12
thats great - able to checkout, build and replicate - leave this with me

**Comment by seanlandsman** [comment] 2016-10-05 14:47
hi - do you want to give ag-grid-ng2@6.1.3-beta - let me know how it goes

thanks

**Comment by DzmitryShylovich** [comment] 2016-10-05 14:56
Works fine 👍

**Comment by seanlandsman** [comment] 2016-10-05 15:02
woohoo - thanks for your assistance with this 

We'll follow up shortly with a full release

**Comment by DzmitryShylovich** [comment] 2016-10-05 15:03
Cool thx.

**Comment by DzmitryShylovich** [comment] 2016-10-05 16:07
@seanlandsman 
[these](https://github.com/ceolter/ag-grid-ng2/blob/master/src/aggrid.module.ts#L18) providers should go into `forRoot()` method as well. So I would suggest you to create 2 methods with meaningful names like [here](https://github.com/ngrx/store-devtools/blob/master/src/instrument.ts#L79): 1 for jit and 2 for aot users.

**Comment by seanlandsman** [comment] 2016-10-05 16:47
Yes, thanks - the version I'll release will have both these points handled. The main thing from this beta was just to verify it works as expected

But thank you for the feedback - its always welcome!

**Comment by seanlandsman** [comment] 2016-10-05 18:49
Hi - final note - 6.1.1 release. Please see https://www.ag-grid.com/best-angular-2-data-grid/#aot for more details, but tl;dr:

        AgGridModule.withAotSupport()

Is what you'll probably want to use

Thanks again for your help

**Closed by seanlandsman** 2016-10-05 18:49 UTC

**Comment by DzmitryShylovich** [comment] 2016-10-05 19:40
You can also dynamically create components using `ComponentFactoryResolver` and it will work with aot. Have u tried such option?

**Comment by seanlandsman** [comment] 2016-10-05 20:10
Thanks for the heads up - I was looking at alternatives as I really didnt want an aot/non aot option

This is something I'm trying now - hopefully I can remove the two options and end up with one option for both!

I was keen to get something out though as lack of aot support was a blocker for some of our users

**Comment by seanlandsman** [comment] 2016-10-05 20:16
the immediate problem I see with this is that I wouldnt be able to pass in module imports - this would make using other directives a bit harder (ie ngIf) - still early days though

**Comment by DzmitryShylovich** [comment] 2016-10-05 21:52
> he immediate problem I see with this is that I wouldnt be able to pass in module imports - this would make using other directives a bit harder (ie ngIf)

I'm not sure I fully understand the issue but looking at the [sources](https://github.com/ceolter/ag-grid-ng2/blob/master/src/ng2ComponentFactory.ts#L273) for me it's an overkill to dynamically create a module and compile it.

For example: http://plnkr.co/edit/kkM1aR4yPcIqeBhamoDW?p=preview
Isn't it enough to render a cell from user provided component?

**Comment by DzmitryShylovich** [comment] 2016-10-05 22:30
And I also think creating separate component for every cell is a boilerplate. Imho the best api for custom cell templates is `<template>` element. 
Examples: [angular2-data-table](https://swimlane.gitbooks.io/angular2-data-table/content/examples/expressive.html)

**Comment by seanlandsman** [comment] 2016-10-06 07:08
Ok, to answer both:

- Yes, we're considering this - the problem is that many of our users want to be able to use  other components in their components.  ie if they wanted to use ngStyle they need to be able to pass in CommonModule - and for this to work we need to create a module in the background. If the component is isolated with no dependencies (as with your HelloComponent) then  yes, we definately dont need to create a new module & component. It might be a good idea to provide this as an option at least so users can use AOT and "simple" components. Does this make sesnse?

- We're actually looking to provide a declarative option in ag-grid too - work on this will start today :-)

Keep in mind we're trying to accommodate many different requirements here - some users are happy with a template string as you suggest, others require much richer components. 

All that said this is still a fluid implementation - I'm learning a great deal about what options I have and am always trying to improve what we have. With regards creating new components I'm also investigating how this might be improved - again, learning as I go :-)

I'm hoping that we'll able to provide simple components and templates with AOT - this would be the best we could offer here I think. We could then also offer rich components, with the trade off that AOT couldnt be used.

I am not happy with **no** dynamic cell and AOT - I'm working on changing this

**Comment by DzmitryShylovich** [comment] 2016-10-06 10:03
> Yes, we're considering this - the problem is that many of our users want to be able to use other components in their components. ie if they wanted to use ngStyle they need to be able to pass in CommonModule - and for this to work we need to create a module in the background. If the component is isolated with no dependencies (as with your HelloComponent) then yes, we definately dont need to create a new module & component. It might be a good idea to provide this as an option at least so users can use AOT and "simple" components. Does this make sesnse?

ok, extended example http://plnkr.co/edit/kkM1aR4yPcIqeBhamoDW?p=preview
Every component in angular have to be a part of some module so there's no need to dynamically create modules. User just have to add his component into `@NgModule.entryComponents` and voila.

**Comment by seanlandsman** [comment] 2016-10-06 10:38
Nice, I like this. I'll have to put this aside for now, but will definitely try this (and other) avenues early next week

I'm pretty sure I'll have something that achieves what we're after here - thanks for the pointers

**Comment by petrosus** [comment] 2016-10-13 08:39
Hi, is there any update on this?

I have started a angular2 project with customized ng2 components for filtering in ag-grid and this is rely a showstoper for whole project.

**Comment by seanlandsman** [comment] 2016-10-13 08:44
As it stands you can either have AOT and no angular 2 components, or angular 2 and no AOT. I'm hoping to investigate this further to provide a single offering soon, but at the moment I'm afraid these are your choices at the moment

**Comment by pdavin** [comment] 2017-01-12 18:09
@seanlandsman Could you point me to where the solution this issue was resolved with got moved to?  
>
https://www.ag-grid.com/best-angular-2-data-grid/#aot for more details, but tl;dr:

    AgGridModule.withAotSupport()
<

The above link is invalid (#aot section no longer exists) and AgGridModule.withAotSupport() is an undefined function. I found a couple blog posts on v7 AOT, but they explain how to use Angular 2 components inside ag-grid with AOT.  I don't want to do that, I just want to get ag-grid + ag-grid-ng2 working with AOT. That's not working due to https://github.com/ceolter/ag-grid-ng2/issues/112

How does one setup ag-grid in an Angular 2 AoT app?

**Comment by seanlandsman** [comment] 2017-01-12 18:22
@pdavin ag-grid-ng2 works just fine with AOT, it just doesn't appear to work with rollup.

If you take at the https://github.com/ceolter/ag-grid-ng2-example repo you'll find examples where it works with AOT (for example, the systemjs example for example uses systemjs-builder for rollup)

**Comment by pdavin** [comment] 2017-01-12 18:42
Yes, it's unfortunate there are so many competing ways to build AOT :(  
We're using rollup because I couldn't get @ngtools/webpack to work (which is basically a standalone offshoot of angular-cli). I guess I should look into switching away from rollup. But it's a very expensive proposition because switching the AoT build environment generally triggers dozens of obscure errors and integration problems in my experience. 

I didn't know about the systemjs-builder approach though. I haven't found many projects using this method though, and one example project deprecated it in favor of angular-cli webpack. So if I have time I should probably try angular-cli first (which is almost the same as @ngtools/webpack which I already tried, but perhaps will be easier).

**Comment by seanlandsman** [comment] 2017-01-12 18:47
Its maybe work looking at the angular-cli example too - this works and seems to becoming the standard (slowly) way to build angular apps. As a matter of interest the resulting bundle sizes with systemjs-builder, webpack and angular cli were all comparable (not far off in size). Of course I can't compare this to what it might be with rollup at the moment.

Please note that looking and at a working rollup example is on the list, but isn't something I'll realistically get to soon I'm afraid (in the interests of setting expectations here)
